name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history and metadata
      run: |
        git fetch --prune --unshallow
        git checkout -b pr
        git branch -f main origin/main

    - name: Install clang-format
      run: |
        sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-proposed restricted main multiverse universe' >> /etc/apt/sources.list.d/proposed-repositories.list"
        sudo apt-get update -q
        sudo apt-get install -y clang-format-12

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install wpiformat
      run: pip3 install wpiformat

    - name: Run wpiformat
      run: wpiformat -clang 12

    - name: Verify wpiformat made no changes
      run: git --no-pager diff --exit-code HEAD
